package com.g1.sketchbook

import android.app.Application
import com.g1.sketchbook.auth.GoogleAuthClient
import com.g1.sketchbook.data.SessionStore

/** Simple manual DI container. Held by the Application so ViewModels can reach shared singletons. */
class Graph(app: Application) {
    val sessionStore = SessionStore(app)
    val authClient = GoogleAuthClient(
        context = app,
        // Auto-generated by the google-services plugin from google-services.json (web OAuth client).
        webClientId = app.getString(R.string.default_web_client_id),
    )
}

class SketchApp : Application() {
    lateinit var graph: Graph
        private set

    override fun onCreate() {
        super.onCreate()
        graph = Graph(this)
    }
}
